#!/bin/bash

if [ -n "$1" ]; then
    if [ -r "$1" ]; then
	    exec 3<"$1"
	    echo -en "\E[1;31mReading lines from file: $1\E[0m\n" >&2
    else
	    echo -en "\E[1;31m$( basename $0 ): $1: No such file\E[0m\n" >&2
	exit 1
    fi
else 
    exec 3<&0
    echo -en "\E[1;31mReading lines from stdin\E[0m\n" >&2
fi

linecount=0
while read line
do
	echo "line: $line"
	(( linecount++ ))
done <&3
echo line count: $linecount

